### ISSUE TITLE
Connexion problem

### ISSUE THREAD

**Issue by 5chacha5** [lapixo/homebridge-bsblan-thermostat#2]
Hi,

I have a problem with this plugin :
[3/3/2021, 11:25:58 PM] [Thermostat-Etage] Error getting status: ESOCKETTIMEDOUT
[3/3/2021, 11:25:58 PM] [Thermostat-RDC] Error getting status: ESOCKETTIMEDOUT

The request is set to "pollInterval": 60 for each thermostat.

how I can solve it ?

Thanks

**Comment by lapixo** [comment]
Hi,
if you have more than one thermostat configured, you should set the interval to different values. 
(40 sec, 45 sec, 50 sec, 55 sec) and so on...
Thermostat-Etage to 40 sec
Thermostat-RDC to 55 sec

The Problem is, that after 60 seconds all your configured thermostat plugins call the BSB Lan at the same time but the bsb lan can only process one call at the same time.

**Comment by 5chacha5** [comment]
> Hi,
> if you have more than one thermostat configured, you should set the interval to different values.
> (40 sec, 45 sec, 50 sec, 55 sec) and so on...
> Thermostat-Etage to 40 sec
> Thermostat-RDC to 55 sec
> 
> The Problem is, that after 60 seconds all your configured thermostat plugins call the BSB Lan at the same time but the bsb lan can only process one call at the same time.

Thanks a lot that's ok

**Comment by 5chacha5** [comment]
Hi 

can we set current temperature via listener with this plugin ? That must modify port 10000 on bsb lan...? Or which plugin I can use to do it ? Information of temperature come from Shelly H&T... thanks

**Comment by lapixo** [comment]
Hi, you can only read the values from the listener. 

i don't know with plugin you can use for that.
